#!/usr/bin/env bash

function lxc_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      export GOPATH="$shome/vendor/go"
      export PATH="$GOPATH/bin:$PATH"
      go get -v "github.com/lxc/lxd"
      cd "$GOPATH/src"
      (cd github.com/lxc/lxd && git fetch --tags && git reset --hard lxd-${LXD_VERSION})
      go get -v "github.com/lxc/lxd/lxc/..."
      go install -v "github.com/lxc/lxd/lxc/..."

      mkdir -p "$shome/bin"
      (set +f; cp $GOPATH/bin/* "$shome/bin/")
      rm -rf "$GOPATH"
      ;;

    Linux)
      sudo env - add-apt-repository ppa:ubuntu-lxc/lxd-stable
      sudo aptitude update -y
      sudo aptitude install -y lxd
      ;;
  esac
}

lxc_bootstrap "$@"
