#!/usr/bin/env bash

function lxc_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  set -x
  case "${DISTRIB_ID}" in
    Ubuntu)
      ${NOSUDO} sudo apt-mark unhold lxd 2>/dev/null 1>&2 || true
      ${NOSUDO} sudo env - add-apt-repository ppa:ubuntu-lxc/lxd-stable
      ${NOSUDO} sudo apt-get update -y
      ${NOSUDO} sudo apt-get install -y lxd="${LXD_VERSION}-*" lxd-client="${LXD_VERSION}-*"
      ${NOSUDO} sudo apt-mark hold lxd
      ;;
    *)
      export GOPATH="$shome/vendor/go"
      export PATH="$GOPATH/bin:$PATH"
      go get -v "github.com/lxc/lxd"
      cd "$GOPATH/src"
      (cd github.com/lxc/lxd && git fetch --tags && git reset --hard lxd-${LXD_VERSION})
      go get -v "github.com/lxc/lxd/lxc/..."
      go install -v "github.com/lxc/lxd/lxc/..."

      mkdir -p "$shome/bin"
      (set +f; cp $GOPATH/bin/* "$shome/bin/")
      rm -rf "$GOPATH"
      ;;
  esac
}

lxc_bootstrap "$@"
