#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Ubuntu)
      if ! type -P lxc >/dev/null; then
        return 1
      fi
      ;;
    *)
      if [[ "$($shome/script/version | jq -r '.lxd')" != "$LXD_VERSION" ]]; then
        return 1
      fi
      ;;
  esac

  return 0
}

source sub "$BASH_SOURCE" "$@"
