#!/usr/bin/env bash

function _lxc_profile {
  local shome="${_lxc_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  LXD_VERSION='2.16'
  LXD_UBUNTU_VERSION='2.16-0ubuntu2~ubuntu16.04.1~ppa1'
}

_lxc_profile
