#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lxd="$(lxc --version 2>/dev/null || true)"
  jq -n --arg lxd "$ver_lxd" '{lxd: $lxd}'
}

version "$@"
